---
- name: add rpm keys
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Add rpm repositories
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ rpm_repositories }}"
  when: item is search('\\.rpm') 

- name: Add .repo files directly 
  get_url:
    url: "{{ item }}"
    dest: /etc/yum.repos.d
  loop: "{{ rpm_repositories }}"
  when: item is search('\\.repo') 

- name: add vcode studio repo   
  template:
    src: vscode.repo.j2
    dest: /etc/yum.repos.d/vscode.repo
